FROM docker.io/library/ubuntu:latest

WORKDIR /opt

#meant to be largely a clone of the current python module



RUN \

    apt-get update        && \

    apt-get install --yes    \

        build-essential      \

        git                  \

        gfortran             \

        wget              && \

    apt-get clean all



#anaconda

ARG installer=Anaconda3-2021.11-Linux-x86_64.sh

RUN wget https://repo.anaconda.com/archive/$installer && \

    bash ./$installer -b -p /opt/anaconda3 && \

    rm -rf $installer

ENV PATH=/opt/anaconda3/bin:$PATH



#mpich from source. python installation needs to come first.

ARG mpich=4.0

ARG mpich_prefix=mpich-$mpich

RUN \

    wget https://www.mpich.org/static/downloads/$mpich/$mpich_prefix.tar.gz && \

    tar xvzf $mpich_prefix.tar.gz                                           && \

    cd $mpich_prefix                                                        && \

    export FCFLAGS=-fallow-argument-mismatch && \

    export FFLAGS=-fallow-argument-mismatch && \

    ./configure  && \

    make -j 16                                                              && \

    make install                                                            && \

    make clean                                                              && \

    cd ..                                                                   && \

    rm -rf $mpich_prefix

RUN /sbin/ldconfig



#update conda tool

#remove mpich/mpi that now come with anaconda

RUN conda update --yes conda && \

    conda uninstall mpich mpi --yes && \

    conda install --yes -c conda-forge mamba



#uninstalling mpi removes essential packages, so re-add

RUN mamba install --yes astropy cartopy cython cfitsio dask scipy scikit-learn scikit-image numba h5py matplotlib joblib pandas seaborn s

tatsmodels



#build mpi4py on top of our mpich

RUN python -m pip install mpi4py



#install extra packages for nersc tools, jupyter, sf api, etc

#force security update for ipython

RUN mamba install --yes ipython=7.31.1 -c conda-forge && \

    mamba install --yes ipympl=0.8.6 -c conda-forge && \

    mamba install authlib tabulate psycopg2 -y && \

    mamba install netcdf4 mysql-connector-python -c conda-forge -y && \

    mamba install distributed -c conda-forge -y && \

    mamba install -c conda-forge --no-deps dask-mpi -y



#-# Gather the N10 Benchmark: py-DGEMM

# Background

RUN conda install "blas=*=*mkl" numpy

RUN conda install -c conda-forge cupy cudatoolkit=11.7



RUN git clone https://gitlab.com/NERSC/N10-benchmarks/py-dgemm.git 