#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/utils/jobscript

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q regular
#SBATCH -J dgemm
#SBATCH --mail-user=spachchigar@sfsu.edu
#SBATCH --mail-type=ALL
#SBATCH -A nintern
#SBATCH -t 1:00:0

# OpenMP settings:
export OMP_PLACES=cores
export OMP_PROC_BIND=true

ml PrgEnv-gnu
ml python

#run the application: 
for t in 128
do	
    for nsize in 5000 40000 45000 50000 65536
    do
        echo "Running with nsize=$nsize and OMP_NUM_THREADS=$t"
        export OMP_NUM_THREADS=$t
        srun -n 1 python python-dgemm.py --nsize $nsize --niterations 100
    done
done
