#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/utils/jobscript

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J dgemm
#SBATCH --mail-user=spachchigar@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -A nintern
#SBATCH -t 0:10:0

# OpenMP settings:
export OMP_NUM_THREADS=256
export OMP_PLACES=cores
export OMP_PROC_BIND=true

ml PrgEnv-gnu
ml python

#run the application: 
srun -n 1 -c 256 python python-dgemm.py --nsize 1024 --niterations 100
